package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Admin generated by hbm2java
 */
@Entity
@Table(name="admin"
    ,catalog="chattingapp"
)
public class Admin  implements java.io.Serializable {


     private String phoneNumber;
     private Country country;
     private String name;
     private String email;
     private byte[] picture;
     private String password;
     private byte gender;
     private Date dateOfBirth;
     private String biography;

    public Admin() {
    }

	
    public Admin(String phoneNumber, Country country, String name, String password, byte gender, Date dateOfBirth) {
        this.phoneNumber = phoneNumber;
        this.country = country;
        this.name = name;
        this.password = password;
        this.gender = gender;
        this.dateOfBirth = dateOfBirth;
    }
    public Admin(String phoneNumber, Country country, String name, String email, byte[] picture, String password, byte gender, Date dateOfBirth, String biography) {
       this.phoneNumber = phoneNumber;
       this.country = country;
       this.name = name;
       this.email = email;
       this.picture = picture;
       this.password = password;
       this.gender = gender;
       this.dateOfBirth = dateOfBirth;
       this.biography = biography;
    }
   
     @Id 

    
    @Column(name="phone_number", unique=true, nullable=false, length=16)
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="country_id", nullable=false)
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="name", nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="email", length=80)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="picture")
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    
    @Column(name="password", nullable=false, length=80)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="gender", nullable=false)
    public byte getGender() {
        return this.gender;
    }
    
    public void setGender(byte gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date_of_birth", nullable=false, length=10)
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }

    
    @Column(name="biography", length=65535)
    public String getBiography() {
        return this.biography;
    }
    
    public void setBiography(String biography) {
        this.biography = biography;
    }




}


