package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatGroupMessagesId generated by hbm2java
 */
@Embeddable
public class ChatGroupMessagesId  implements java.io.Serializable {


     private int groupId;
     private String senderPhoneNumber;
     private Date timestamp;

    public ChatGroupMessagesId() {
    }

    public ChatGroupMessagesId(int groupId, String senderPhoneNumber, Date timestamp) {
       this.groupId = groupId;
       this.senderPhoneNumber = senderPhoneNumber;
       this.timestamp = timestamp;
    }
   


    @Column(name="group_id", nullable=false, length=16)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


    @Column(name="sender_phone_number", nullable=false)
    public String getSenderPhoneNumber() {
        return this.senderPhoneNumber;
    }
    
    public void setSenderPhoneNumber(String senderPhoneNumber) {
        this.senderPhoneNumber = senderPhoneNumber;
    }


    @Column(name="timestamp", nullable=false, length=26)
    public Date getTimestamp() {
        return this.timestamp;
    }
    
    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChatGroupMessagesId) ) return false;
		 ChatGroupMessagesId castOther = ( ChatGroupMessagesId ) other; 
         
		 return (this.getGroupId()==castOther.getGroupId())
 && ( (this.getSenderPhoneNumber()==castOther.getSenderPhoneNumber()) || ( this.getSenderPhoneNumber()!=null && castOther.getSenderPhoneNumber()!=null && this.getSenderPhoneNumber().equals(castOther.getSenderPhoneNumber()) ) )
 && ( (this.getTimestamp()==castOther.getTimestamp()) || ( this.getTimestamp()!=null && castOther.getTimestamp()!=null && this.getTimestamp().equals(castOther.getTimestamp()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getGroupId();
         result = 37 * result + ( getSenderPhoneNumber() == null ? 0 : this.getSenderPhoneNumber().hashCode() );
         result = 37 * result + ( getTimestamp() == null ? 0 : this.getTimestamp().hashCode() );
         return result;
   }   


}


