package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ChatGroupMessages generated by hbm2java
 */
@Entity
@Table(name="chat_group_messages"
    ,catalog="chattingapp"
)
public class ChatGroupMessages  implements java.io.Serializable {


     private ChatGroupMessagesId id;
     private ChatGroupUsers chatGroupUsers;
     private String messageContentOrFileName;
     private byte[] file;
     private byte status;

    public ChatGroupMessages() {
    }

	
    public ChatGroupMessages(ChatGroupMessagesId id, ChatGroupUsers chatGroupUsers, String messageContentOrFileName, byte status) {
        this.id = id;
        this.chatGroupUsers = chatGroupUsers;
        this.messageContentOrFileName = messageContentOrFileName;
        this.status = status;
    }
    public ChatGroupMessages(ChatGroupMessagesId id, ChatGroupUsers chatGroupUsers, String messageContentOrFileName, byte[] file, byte status) {
       this.id = id;
       this.chatGroupUsers = chatGroupUsers;
       this.messageContentOrFileName = messageContentOrFileName;
       this.file = file;
       this.status = status;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="groupId", column=@Column(name="group_id", nullable=false, length=16) ), 
        @AttributeOverride(name="senderPhoneNumber", column=@Column(name="sender_phone_number", nullable=false) ), 
        @AttributeOverride(name="timestamp", column=@Column(name="timestamp", nullable=false, length=26) ) } )
    public ChatGroupMessagesId getId() {
        return this.id;
    }
    
    public void setId(ChatGroupMessagesId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="group_id", referencedColumnName="user_phone_number", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="sender_phone_number", referencedColumnName="group_id", nullable=false, insertable=false, updatable=false) } )
    public ChatGroupUsers getChatGroupUsers() {
        return this.chatGroupUsers;
    }
    
    public void setChatGroupUsers(ChatGroupUsers chatGroupUsers) {
        this.chatGroupUsers = chatGroupUsers;
    }

    
    @Column(name="message_content_or_file_name", nullable=false, length=65535)
    public String getMessageContentOrFileName() {
        return this.messageContentOrFileName;
    }
    
    public void setMessageContentOrFileName(String messageContentOrFileName) {
        this.messageContentOrFileName = messageContentOrFileName;
    }

    
    @Column(name="file")
    public byte[] getFile() {
        return this.file;
    }
    
    public void setFile(byte[] file) {
        this.file = file;
    }

    
    @Column(name="status", nullable=false)
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


