package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChatGroup generated by hbm2java
 */
@Entity
@Table(name="chat_group"
    ,catalog="chattingapp"
)
public class ChatGroup  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;
     private byte[] picture;
     private Date lastMessageSentTime;
     private Set<ChatGroupUsers> chatGroupUserses = new HashSet<ChatGroupUsers>(0);

    public ChatGroup() {
    }

	
    public ChatGroup(User user, String name) {
        this.user = user;
        this.name = name;
    }
    public ChatGroup(User user, String name, byte[] picture, Date lastMessageSentTime, Set<ChatGroupUsers> chatGroupUserses) {
       this.user = user;
       this.name = name;
       this.picture = picture;
       this.lastMessageSentTime = lastMessageSentTime;
       this.chatGroupUserses = chatGroupUserses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="owner_phone_number", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="name", nullable=false)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="picture")
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_message_sent_time", length=26)
    public Date getLastMessageSentTime() {
        return this.lastMessageSentTime;
    }
    
    public void setLastMessageSentTime(Date lastMessageSentTime) {
        this.lastMessageSentTime = lastMessageSentTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chatGroup")
    public Set<ChatGroupUsers> getChatGroupUserses() {
        return this.chatGroupUserses;
    }
    
    public void setChatGroupUserses(Set<ChatGroupUsers> chatGroupUserses) {
        this.chatGroupUserses = chatGroupUserses;
    }




}


