package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ChatGroupUsersId generated by hbm2java
 */
@Embeddable
public class ChatGroupUsersId  implements java.io.Serializable {


     private String userPhoneNumber;
     private int groupId;

    public ChatGroupUsersId() {
    }

    public ChatGroupUsersId(String userPhoneNumber, int groupId) {
       this.userPhoneNumber = userPhoneNumber;
       this.groupId = groupId;
    }
   


    @Column(name="user_phone_number", nullable=false, length=16)
    public String getUserPhoneNumber() {
        return this.userPhoneNumber;
    }
    
    public void setUserPhoneNumber(String userPhoneNumber) {
        this.userPhoneNumber = userPhoneNumber;
    }


    @Column(name="group_id", nullable=false)
    public int getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(int groupId) {
        this.groupId = groupId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ChatGroupUsersId) ) return false;
		 ChatGroupUsersId castOther = ( ChatGroupUsersId ) other; 
         
		 return ( (this.getUserPhoneNumber()==castOther.getUserPhoneNumber()) || ( this.getUserPhoneNumber()!=null && castOther.getUserPhoneNumber()!=null && this.getUserPhoneNumber().equals(castOther.getUserPhoneNumber()) ) )
 && (this.getGroupId()==castOther.getGroupId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUserPhoneNumber() == null ? 0 : this.getUserPhoneNumber().hashCode() );
         result = 37 * result + this.getGroupId();
         return result;
   }   


}


