package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ChatGroupUsers generated by hbm2java
 */
@Entity
@Table(name="chat_group_users"
    ,catalog="chattingapp"
)
public class ChatGroupUsers  implements java.io.Serializable {


     private ChatGroupUsersId id;
     private ChatGroup chatGroup;
     private User user;
     private String fontFamily;
     private Short fontSize;
     private Integer fontColor;
     private Byte boldFlag;
     private Byte underlineFlag;
     private Byte italicFlag;
     private byte[] textBackground;
     private Set<ChatGroupMessages> chatGroupMessageses = new HashSet<ChatGroupMessages>(0);

    public ChatGroupUsers() {
    }

	
    public ChatGroupUsers(ChatGroupUsersId id, ChatGroup chatGroup, User user) {
        this.id = id;
        this.chatGroup = chatGroup;
        this.user = user;
    }
    public ChatGroupUsers(ChatGroupUsersId id, ChatGroup chatGroup, User user, String fontFamily, Short fontSize, Integer fontColor, Byte boldFlag, Byte underlineFlag, Byte italicFlag, byte[] textBackground, Set<ChatGroupMessages> chatGroupMessageses) {
       this.id = id;
       this.chatGroup = chatGroup;
       this.user = user;
       this.fontFamily = fontFamily;
       this.fontSize = fontSize;
       this.fontColor = fontColor;
       this.boldFlag = boldFlag;
       this.underlineFlag = underlineFlag;
       this.italicFlag = italicFlag;
       this.textBackground = textBackground;
       this.chatGroupMessageses = chatGroupMessageses;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="userPhoneNumber", column=@Column(name="user_phone_number", nullable=false, length=16) ), 
        @AttributeOverride(name="groupId", column=@Column(name="group_id", nullable=false) ) } )
    public ChatGroupUsersId getId() {
        return this.id;
    }
    
    public void setId(ChatGroupUsersId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false, insertable=false, updatable=false)
    public ChatGroup getChatGroup() {
        return this.chatGroup;
    }
    
    public void setChatGroup(ChatGroup chatGroup) {
        this.chatGroup = chatGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_phone_number", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="font_family")
    public String getFontFamily() {
        return this.fontFamily;
    }
    
    public void setFontFamily(String fontFamily) {
        this.fontFamily = fontFamily;
    }

    
    @Column(name="font_size")
    public Short getFontSize() {
        return this.fontSize;
    }
    
    public void setFontSize(Short fontSize) {
        this.fontSize = fontSize;
    }

    
    @Column(name="font_color")
    public Integer getFontColor() {
        return this.fontColor;
    }
    
    public void setFontColor(Integer fontColor) {
        this.fontColor = fontColor;
    }

    
    @Column(name="bold_flag")
    public Byte getBoldFlag() {
        return this.boldFlag;
    }
    
    public void setBoldFlag(Byte boldFlag) {
        this.boldFlag = boldFlag;
    }

    
    @Column(name="underline_flag")
    public Byte getUnderlineFlag() {
        return this.underlineFlag;
    }
    
    public void setUnderlineFlag(Byte underlineFlag) {
        this.underlineFlag = underlineFlag;
    }

    
    @Column(name="italic_flag")
    public Byte getItalicFlag() {
        return this.italicFlag;
    }
    
    public void setItalicFlag(Byte italicFlag) {
        this.italicFlag = italicFlag;
    }

    
    @Column(name="text_background")
    public byte[] getTextBackground() {
        return this.textBackground;
    }
    
    public void setTextBackground(byte[] textBackground) {
        this.textBackground = textBackground;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="chatGroupUsers")
    public Set<ChatGroupMessages> getChatGroupMessageses() {
        return this.chatGroupMessageses;
    }
    
    public void setChatGroupMessageses(Set<ChatGroupMessages> chatGroupMessageses) {
        this.chatGroupMessageses = chatGroupMessageses;
    }




}


