package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
    ,catalog="chattingapp"
    , uniqueConstraints = @UniqueConstraint(columnNames="name") 
)
public class Country  implements java.io.Serializable {


     private byte id;
     private String name;
     private Set<Admin> admins = new HashSet<Admin>(0);
     private Set<User> users = new HashSet<User>(0);

    public Country() {
    }

	
    public Country(byte id, String name) {
        this.id = id;
        this.name = name;
    }
    public Country(byte id, String name, Set<Admin> admins, Set<User> users) {
       this.id = id;
       this.name = name;
       this.admins = admins;
       this.users = users;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="name", unique=true, nullable=false, length=80)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Admin> getAdmins() {
        return this.admins;
    }
    
    public void setAdmins(Set<Admin> admins) {
        this.admins = admins;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<User> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<User> users) {
        this.users = users;
    }




}


