package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FriendId generated by hbm2java
 */
@Embeddable
public class FriendId  implements java.io.Serializable {


     private String phoneNumber1;
     private String phoneNumber2;

    public FriendId() {
    }

    public FriendId(String phoneNumber1, String phoneNumber2) {
       this.phoneNumber1 = phoneNumber1;
       this.phoneNumber2 = phoneNumber2;
    }
   


    @Column(name="phone_number1", nullable=false, length=16)
    public String getPhoneNumber1() {
        return this.phoneNumber1;
    }
    
    public void setPhoneNumber1(String phoneNumber1) {
        this.phoneNumber1 = phoneNumber1;
    }


    @Column(name="phone_number2", nullable=false, length=16)
    public String getPhoneNumber2() {
        return this.phoneNumber2;
    }
    
    public void setPhoneNumber2(String phoneNumber2) {
        this.phoneNumber2 = phoneNumber2;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FriendId) ) return false;
		 FriendId castOther = ( FriendId ) other; 
         
		 return ( (this.getPhoneNumber1()==castOther.getPhoneNumber1()) || ( this.getPhoneNumber1()!=null && castOther.getPhoneNumber1()!=null && this.getPhoneNumber1().equals(castOther.getPhoneNumber1()) ) )
 && ( (this.getPhoneNumber2()==castOther.getPhoneNumber2()) || ( this.getPhoneNumber2()!=null && castOther.getPhoneNumber2()!=null && this.getPhoneNumber2().equals(castOther.getPhoneNumber2()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPhoneNumber1() == null ? 0 : this.getPhoneNumber1().hashCode() );
         result = 37 * result + ( getPhoneNumber2() == null ? 0 : this.getPhoneNumber2().hashCode() );
         return result;
   }   


}


