package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OneToOneMessageStatus generated by hbm2java
 */
@Entity
@Table(name="one_to_one_message_status"
    ,catalog="chattingapp"
    , uniqueConstraints = @UniqueConstraint(columnNames="description") 
)
public class OneToOneMessageStatus  implements java.io.Serializable {


     private byte id;
     private String description;

    public OneToOneMessageStatus() {
    }

    public OneToOneMessageStatus(byte id, String description) {
       this.id = id;
       this.description = description;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="description", unique=true, nullable=false, length=80)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


