package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OneToOneMessagesId generated by hbm2java
 */
@Embeddable
public class OneToOneMessagesId  implements java.io.Serializable {


     private String senderPhoneNumber;
     private String receiverPhoneNumber;

    public OneToOneMessagesId() {
    }

    public OneToOneMessagesId(String senderPhoneNumber, String receiverPhoneNumber) {
       this.senderPhoneNumber = senderPhoneNumber;
       this.receiverPhoneNumber = receiverPhoneNumber;
    }
   


    @Column(name="sender_phone_number", nullable=false, length=16)
    public String getSenderPhoneNumber() {
        return this.senderPhoneNumber;
    }
    
    public void setSenderPhoneNumber(String senderPhoneNumber) {
        this.senderPhoneNumber = senderPhoneNumber;
    }


    @Column(name="receiver_phone_number", nullable=false, length=16)
    public String getReceiverPhoneNumber() {
        return this.receiverPhoneNumber;
    }
    
    public void setReceiverPhoneNumber(String receiverPhoneNumber) {
        this.receiverPhoneNumber = receiverPhoneNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OneToOneMessagesId) ) return false;
		 OneToOneMessagesId castOther = ( OneToOneMessagesId ) other; 
         
		 return ( (this.getSenderPhoneNumber()==castOther.getSenderPhoneNumber()) || ( this.getSenderPhoneNumber()!=null && castOther.getSenderPhoneNumber()!=null && this.getSenderPhoneNumber().equals(castOther.getSenderPhoneNumber()) ) )
 && ( (this.getReceiverPhoneNumber()==castOther.getReceiverPhoneNumber()) || ( this.getReceiverPhoneNumber()!=null && castOther.getReceiverPhoneNumber()!=null && this.getReceiverPhoneNumber().equals(castOther.getReceiverPhoneNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSenderPhoneNumber() == null ? 0 : this.getSenderPhoneNumber().hashCode() );
         result = 37 * result + ( getReceiverPhoneNumber() == null ? 0 : this.getReceiverPhoneNumber().hashCode() );
         return result;
   }   


}


