package com.imagine.chattingapp.server.dal.entity;
// Generated Mar 11, 2019 12:40:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * RequestStatus generated by hbm2java
 */
@Entity
@Table(name="request_status"
    ,catalog="chattingapp"
    , uniqueConstraints = @UniqueConstraint(columnNames="description") 
)
public class RequestStatus  implements java.io.Serializable {


     private byte id;
     private String description;
     private Set<FriendRequest> friendRequests = new HashSet<FriendRequest>(0);

    public RequestStatus() {
    }

	
    public RequestStatus(byte id, String description) {
        this.id = id;
        this.description = description;
    }
    public RequestStatus(byte id, String description, Set<FriendRequest> friendRequests) {
       this.id = id;
       this.description = description;
       this.friendRequests = friendRequests;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }

    
    @Column(name="description", unique=true, nullable=false, length=80)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="requestStatus")
    public Set<FriendRequest> getFriendRequests() {
        return this.friendRequests;
    }
    
    public void setFriendRequests(Set<FriendRequest> friendRequests) {
        this.friendRequests = friendRequests;
    }




}


